# Generated by Django 4.1.1 on 2022-11-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classCapacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='classEnrollment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='classSpotsOpen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='waitlist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='waitlistMax',
            field=models.IntegerField(default=0),
        ),
    ]
