# Generated by Django 4.1.1 on 2022-11-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_classcapacity_course_classenrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='activeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activeUser', to='main.myuser'),
        ),
    ]
