# Generated by Django 3.2.16 on 2022-10-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221020_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseSection',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructorEmail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructorName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='lectureType',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='meeting_days',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='room_location',
            field=models.CharField(max_length=100),
        ),
    ]
