# Generated by Django 3.2.16 on 2022-10-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20221020_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meeting_days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='room_location',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
    ]
