# Generated by Django 3.2.16 on 2022-10-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20221020_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='meeting_days',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='room_location',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
