# Generated by Django 4.1.1 on 2022-10-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20221020_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='updateProfile',
            field=models.BooleanField(default=1),
        ),
    ]
