# Generated by Django 4.1.1 on 2022-10-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_myuser_updateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='updateProfile',
        ),
    ]
