# Generated by Django 4.1.1 on 2022-10-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_myuser_updateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='main.myuser'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='numFriends',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='schedule',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='myuser',
            name='shoppingcart',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Friend_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='main.myuser')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='main.myuser')),
            ],
        ),
    ]
