# Generated by Django 4.1.1 on 2022-11-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_myuser_friends_myuser_numfriends_myuser_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(blank=True, default='', to='main.myuser'),
        ),
    ]
