# Generated by Django 4.1.1 on 2022-11-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_myuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='friends',
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.myuser')),
                ('friends', models.ManyToManyField(blank=True, default='', related_name='friends', to='main.myuser')),
            ],
        ),
    ]
