# Generated by Django 4.1.1 on 2022-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_myuser_shoppingcart_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='courseNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
