# Generated by Django 4.1.1 on 2022-11-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_course_id_alter_course_coursenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='courses',
            field=models.ManyToManyField(blank=True, default='', related_name='courses', to='main.course'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='main.myuser'),
        ),
    ]
