# Generated by Django 4.1.1 on 2022-11-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='user',
            new_name='activeUser',
        ),
    ]
