# Generated by Django 4.1.1 on 2022-11-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_user_shoppingcart_activeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=30),
        ),
    ]
