# Generated by Django 4.1.1 on 2022-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classCapacity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='classEnrollment',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='classSpotsOpen',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructorEmail',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='semesterCode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='waitlist',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='waitlistMax',
            field=models.IntegerField(blank=True),
        ),
    ]
