# Generated by Django 4.1.1 on 2022-11-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_course_classcapacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classCapacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='classEnrollment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='classSpotsOpen',
        ),
        migrations.RemoveField(
            model_name='course',
            name='waitlist',
        ),
        migrations.RemoveField(
            model_name='course',
            name='waitlistMax',
        ),
    ]
