# Generated by Django 4.1.1 on 2022-11-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_course_classcapacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='catalogNumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
