# Generated by Django 4.1.1 on 2022-11-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_course_catalognumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='courses',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='coursesInCart',
            field=models.ManyToManyField(blank=True, default='', related_name='coursesInCart', to='main.course'),
        ),
    ]
